service: banking-resource-api
provider:
  name: aws
  environment:
    RUN_AS_LAMBDA: true
    DB_USER: root
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: banking
    DB_HOST: database-1.c0jnsynkz254.ap-south-1.rds.amazonaws.com
    DB_PORT: 4406
  runtime: go1.x
  region: ap-south-1
package:
  patterns:
    - "!./**"
    - "./bin/**"
useDotenv: true
functions:
  bankingresource:
    handler: bin/main
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
