service: goserverlesslambda
provider:
  name: aws
  runtime: go1.x
  region: ap-south-1
package:
  patterns:
    - "!./**"
    - "./bin/**"
useDotenv: true
functions:
  goserverlesslambda:
    handler: bin/goserverlesslambda
    events:
      - http:
          path: /
          method: post
          cors: true
          private: false
