# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint@latest

    - name: Build
      working-directory: ./banking-resource-api    
      run: go build -v ./...

    - name: Test With Coverage
      working-directory: ./banking-resource-api
      run: go test -v -coverprofile=coverage.txt ./...
